FROM python:3.13-slim
WORKDIR /app
COPY ./src .
# Cloud Run will automatically set PORT environment variable
# We expose 8080 as it's the standard for Cloud Run
EXPOSE 8000
# Set environment variables
ENV HOST=0.0.0.0
ENV PORT=8000
ENV PROVIDER=AWS

# Run the application with unbuffered output
CMD ["python", "-u", "main.py"]
