name: Deploy to AWS ECS
on:
  workflow_run:
    workflows: ["Build and Push Image to AWS ECR"]
    types:
      - completed
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::750548848657:role/GitHubActionsDeployRole
          aws-region: ap-southeast-2

      - name: Download current task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: hello-world-3-td
          container-name: hello-world
          image: 750548848657.dkr.ecr.ap-southeast-2.amazonaws.com/learning/hello-world:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: hello-world-3-td-service-2
          cluster: hellow-world-cluster-3
          wait-for-service-stability: true



