name: Build and Push Image to GCP

on:
  push:
    branches:
      - main
    paths:
      - 'api/src/**'
      - 'Dockerfile.prod.gcp'
  workflow_dispatch:

env:
  REGISTRY: australia-southeast1-docker.pkg.dev
  PROJECT_ID: eminent-torch-463904-k0
  PROJECT_NUMBER: 313384425727
  REPOSITORY: hello-world-images
  IMAGE_NAME: hello-world
  WIP_ID: github-actions-pool
  SERVICE_ACCOUNT_NAME: helloworld-github-image-pusher

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WIP_ID }}/providers/github-provider'
          service_account: '${{ env.SERVICE_ACCOUNT_NAME }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.prod.gcp
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest